config/routes.rb
Rails.application.routes.draw do

  resources :flights, only:[:index]
  resources :bookings, only:[:new, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, :class_name=>"Flight", :foreign_key=>"from_airport_id", dependent: :destroy
	has_many :arriving_flights, :class_name=>"Flight", :foreign_key=>"to_airport_id", dependent: :destroy

	validates :airport_code, presence: true, uniqueness: true
	validates :city, presence: true

	default_scope {order(:city)}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :flight
	has_many :passengers, inverse_of: :booking, dependent: :destroy
	accepts_nested_attributes_for :passengers

	validate :passengers_uniqueness

	private
	def passengers_uniqueness		
		self.passengers.each do |p|
			self.flight.bookings.each do |b|
				if b.passengers.find_by(email: p.email)					
					self.errors.add(:passenger, " with email address #{p.email} has already booked this flight.")			
					
				end
			end
		end
	end
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, :class_name => "Airport"
  belongs_to :to_airport, :class_name => "Airport"
  has_many :bookings, inverse_of: :flight


  validates :from_airport_id, presence: true
  validates :to_airport_id, presence: true
  validates :flight_number, presence: true
  validates :start_time, presence: true
  validates :duration_in_minutes, presence: true

  default_scope {order(:start_time)}
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking, inverse_of: :passengers

	before_save{self.email.downcase!}

	validates :name, presence:true, length: {maximum: 255}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html:"Hellow World!"
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  	@passenger_num = params[:passenger_num].to_i
  	@flight = Flight.find(params[:flight])
  	@booking = Booking.new(flight_id: params[:flight])
  	@passenger_num.times {@booking.passengers.build}
  end

  def create
    
  	@booking = Booking.new(booking_params)
  	if !@booking.save
  		@flight = Flight.find(params[:booking][:flight_id])
  		render "new"
  	else
  		flash[:success] = "Your booking is confirmed. The confirmation email was sent to passengers' email box."
      f = @booking.flight
      @booking.passengers.each{|p|
        PassengerMailer.booking_confirmation(f, p).deliver_now
      }
      redirect_to booking_path(@booking)
  	end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
  	params.require(:booking).permit(:flight_id, passengers_attributes:[:id, :name, :email])
  end

 
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  	@airport_options =  Airport.all.map{|a|[[a.city, a.airport_code].join("  "), a.id]}
    @default_date = Flight.first.start_time.to_date

    if !params[:commit].nil?      
      if params[:from].empty? || params[:to].empty?
        flash[:danger] = "Please select both the departing airport and arriving airport."
        redirect_to flights_path
      elsif  params[:from] == params[:to]
        flash[:danger] = "Depart Airport and Arrive Airport can't be the same."
        redirect_to flights_path
      else
        @search = true
        search_date = Date.new(params[:date]["date(1i)"].to_i, params[:date]["date(2i)"].to_i, params[:date]["date(3i)"].to_i)
        @flights = Flight.where("from_airport_id = :from AND to_airport_id = :to", from: params[:from], to: params[:to]).where("start_time >= :date1 AND start_time < :date2", date1: search_date, date2:search_date+1.day)
        @passenger_num = params[:passenger_num]
        if @flights.empty?
          flash[:warning] = "There is no match flight."
          redirect_to flights_path
        end
      end  	
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= render "shared/error_messages", object: @booking %>


<h2>Make Your Booking</h2>

<h3>Your Flight Information</h3>
<table>
		<thead>
			<tr>
				<th>Flight Number</th>
				<th>From</th>
				<th>To</th>
				<th>Start Time</th>
				<th>Duration</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @flight.flight_number %></td>
				<td><%= @flight.from_airport.airport_code %></td>
				<td><%= @flight.to_airport.airport_code %></td>
				<td><%= @flight.start_time %></td>
				<td><%= "#{@flight.duration_in_minutes/60}h #{@flight.duration_in_minutes%60}min" %></td>
			</tr>
		</tbody>
	</table>	

<h3>Passenger Information</h3>

<%= form_for @booking do |f| %>
	
	<%= f.hidden_field :flight_id %>			
	<%= f.fields_for :passengers do |p| %>
		<div>
			<%= "Passenger #{p.index+1}" %>
				<%= p.label :name %>
				<%= p.text_field :name %>
				<%= p.label :email %>
				<%= p.email_field :email %>
		</div>
	<% end %>

	<%= f.submit "Book" %>
<% end %>

app/views/bookings/show.html.erb
<h2>You Booking Information</h2>

<h3>Booking Number: <%= @booking.id %></h3>

<h3>Flight</h3>
<table>
		<thead>
			<tr>
				<th>Flight Number</th>
				<th>From</th>
				<th>To</th>
				<th>Start Time</th>
				<th>Duration</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @booking.flight.flight_number %></td>
				<td><%= @booking.flight.from_airport.airport_code %></td>
				<td><%= @booking.flight.to_airport.airport_code %></td>
				<td><%= @booking.flight.start_time %></td>
				<td><%= "#{@booking.flight.duration_in_minutes/60}h #{@booking.flight.duration_in_minutes%60}min" %></td>
			</tr>
		</tbody>
</table>	

<h3>Passenger</h3>

<table>
	<thead>
		<tr>
			<th>Number</th>
			<th>Name</th>
			<th>Email</th>
		</tr>
	</thead>
	<tbody>
		<% count =1 %>
		<% @booking.passengers.each do |p| %>
			<tr>
				<td><%= count  %></td>
				<% count+=1 %>
				<td><%= p.name %></td>
				<td><%= p.email %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "Back to search", root_path %>

app/views/flights/_flight_search_form.html.erb
<table>
<%= form_tag(flights_path, method: :get)  do %>
	<thead>
		<tr>
			<th><%= label_tag :from, "From" %></th>
			<th><%= label_tag :to, "To" %></th>
			<th><%= label_tag :date, "Date" %></th>
			<th><%= label_tag :passenger_num, "Passengers" %></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= select_tag(:from, options_for_select(@airport_options), prompt:"Select Airport")%></td>
			<td><%= select_tag(:to, options_for_select(@airport_options), prompt:"Select Airport")%></td>
			<td><%= date_select "date", "date", start_year: Time.now.year, end_year: Time.now.year+1, default: @default_date %></td>
			<td><%= select_tag :passenger_num, options_for_select(1..9) %></td>
		</tr>
		<tr>
			<td><%= submit_tag "Search" %></td>
		</tr>	
	</tbody>	
<% end %>
</table>

app/views/flights/_flight_search_result.html.erb
<h2>Pick up a flight</h2>
<%= form_tag(new_booking_path, method: :get) do %>
	<table>
		<thead>
			<tr>
				<th>Select</th>
				<th>Flight Number</th>
				<th>From</th>
				<th>To</th>
				<th>Start Time</th>
				<th>Duration</th>
			</tr>
		</thead>
		<tbody>
			<% @flights.each do |f| %>
					<tr>
						<td><%= radio_button_tag(:flight, f.id) %></td>
						<td><%= label_tag("flight_#{f.id}", f.flight_number) %></td>
						<td><%= f.from_airport.airport_code %></td>
						<td><%= f.to_airport.airport_code %></td>
						<td><%= f.start_time %></td>
						<td><%= "#{f.duration_in_minutes/60}h #{f.duration_in_minutes%60}min" %></td>
					</tr>			
			<% end %>
		</tbody>
	</table>	
	<%= hidden_field_tag :passenger_num, @passenger_num %>
	<%= submit_tag "Select Flight" %>
<% end %>

app/views/flights/index.html.erb
<h2>Flight Search</h2>

<%= render "flight_search_form" %>


<% if @search == true %>
	<%= render "flight_search_result" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |message_type, message| %>
  		<div class="alert alert-<%= message_type %>"><%= message %></div>
  	<% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
 <% if object.errors.any? %> 
  	<div id="error_explanation">
   		 <div class="alert alert-danger">
      			The form contains <%= pluralize(object.errors.count, "error") %>.
    		</div>
  		  <ul>
    			<% object.errors.full_messages.each do |msg| %>
    			  <li><%= msg %></li>
   			 <% end %>
  		</ul>
  	</div>
<% end %>